apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "docker-app.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "docker-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "docker-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "docker-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
      imagePullSecrets:
        {{- if .Values.image.secretName }}
        - name: {{ .Values.image.secretName }}
        {{- else }}
        - name: {{ template "docker-app.fullname" . }}-regsecret
        {{- end -}}